export const seedArticles = [
  {
    id: 'a1',
    title: 'Flamengo vira sobre o Palmeiras e assume a ponta do Brasileirão',
    dek: 'Em noite inspirada no Maracanã, rubro-negro busca virada heroica nos minutos finais e desbanca líder isolado.',
    category: 'Brasileirão',
    author: 'Marcos Villela',
    authorAvatar: 'https://i.pravatar.cc/150?img=12',
    date: '28 de julho de 2026',
    publishedAt: '2026-07-28T21:30:00.000Z',
    readTime: 6,
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=1200&q=80',
    featured: true,
    body: [
      'O Maracanã voltou a tremer na noite deste domingo. Diante de mais de 65 mil torcedores, o Flamengo protagonizou uma daquelas viradas que entram para o anedotário do clube, superando o Palmeiras por 2 a 1 e assumindo, provisoriamente, a ponta da tabela do Campeonato Brasileiro.',
      'O primeiro tempo foi de amplo domínio paulista. Organizado taticamente, o Palmeiras abriu o placar aos 22 minutos em jogada de bola parada, calando a torcida rubro-negra e parecendo, àquela altura, capaz de administrar a vantagem até o apito final.',
      'A virada começou a ser desenhada no intervalo. Mudanças ousadas no meio-campo deram mais verticalidade ao Flamengo, que passou a pressionar a saída de bola adversária com intensidade. O empate saiu aos 31 da etapa final, em finalização de fora da área que explodiu no ângulo.',
      'Nos acréscimos, já com o Maracanã em festa antecipada, o time da casa buscou o gol da virada em contra-ataque fulminante, fechado com categoria pelo camisa 9, que não perdoou a saída precipitada do goleiro.',
      'Com o resultado, o Flamengo chega aos 58 pontos e assume a liderança isolada, à espera dos resultados dos concorrentes diretos ainda nesta rodada. Já o Palmeiras estaciona na terceira colocação e vê a distância aumentar na briga pelo título.',
    ],
    comments: [
      {
        id: 'c1',
        author: 'Rogério T.',
        avatar: 'https://i.pravatar.cc/150?img=23',
        date: 'há 2 horas',
        text: 'Que virada, meu Deus! O Maracanã treme quando o Mengão acredita até o fim.',
        likes: 48,
        replies: [
          {
            id: 'c1r1',
            author: 'Fernanda A.',
            avatar: 'https://i.pravatar.cc/150?img=45',
            date: 'há 1 hora',
            text: 'Torço contra, mas reconheço que foi um segundo tempo espetacular.',
            likes: 12,
            replies: [],
          },
        ],
      },
      {
        id: 'c2',
        author: 'Palmeirense_09',
        avatar: 'https://i.pravatar.cc/150?img=31',
        date: 'há 3 horas',
        text: 'Faltou gerenciamento de jogo no fim. Vacilo coletivo custou caro.',
        likes: 21,
        replies: [],
      },
    ],
  },
  {
    id: 'a2',
    title: 'Seleção Brasileira divulga convocação para as Eliminatórias',
    dek: 'Nomes de peso e novidades na lista para os confrontos decisivos rumo à próxima Copa do Mundo.',
    category: 'Seleção',
    author: 'Camila Duarte',
    authorAvatar: 'https://i.pravatar.cc/150?img=14',
    date: '27 de julho de 2026',
    publishedAt: '2026-07-27T13:00:00.000Z',
    readTime: 4,
    image: 'https://images.unsplash.com/photo-1517927033932-b3d18e61fb3a?auto=format&fit=crop&w=1200&q=80',
    body: [
      'O técnico da Seleção Brasileira anunciou nesta manhã a lista de 26 jogadores convocados para os próximos dois compromissos pelas Eliminatórias.',
      'Entre as novidades, chama atenção a presença de um jovem lateral revelado no futebol paulista, que vive grande fase no seu clube e foi recompensado pelo desempenho consistente nos últimos meses.',
      'A comissão técnica destacou o equilíbrio entre experiência e renovação como pilar da nova convocação, mirando o ciclo de reconstrução após a última competição continental.',
    ],
    comments: [],
  },
  {
    id: 'a3',
    title: 'River Plate e Grêmio fazem duelo equilibrado pela Libertadores',
    dek: 'Times chegam fortes para a partida de ida das quartas de final no Monumental de Núñez.',
    category: 'Libertadores',
    author: 'Diego Fontana',
    authorAvatar: 'https://i.pravatar.cc/150?img=18',
    date: '27 de julho de 2026',
    publishedAt: '2026-07-27T18:00:00.000Z',
    readTime: 5,
    image: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=1200&q=80',
    body: [
      'O Monumental de Núñez recebe hoje um dos confrontos mais aguardados das quartas de final da Libertadores. River Plate e Grêmio protagonizam um duelo histórico entre duas das maiores torcidas do continente.',
      'Ambos os treinadores prometem times ofensivos, apostando na tradição de suas equipes em competições continentais.',
    ],
    comments: [],
  },
  {
    id: 'a4',
    title: 'Crônica: a tarde em que o interior parou para ver um gol de placa',
    dek: 'Resgatamos a história de uma final de campeonato estadual que entrou para a memória afetiva de uma cidade inteira.',
    category: 'Crônica',
    author: 'Heitor Salgado',
    authorAvatar: 'https://i.pravatar.cc/150?img=22',
    date: '26 de julho de 2026',
    publishedAt: '2026-07-26T15:00:00.000Z',
    readTime: 8,
    image: 'https://images.unsplash.com/photo-1489944440615-453fc2b6a1a7?auto=format&fit=crop&w=1200&q=80',
    body: [
      'Havia algo de sagrado nas tardes de domingo daquele campeonato estadual. As famílias chegavam cedo, os bares do entorno lotavam, e o gramado esburacado ganhava contornos de Maracanã aos olhos de quem ali estava.',
      'Foi numa dessas tardes que o camisa 10 recebeu a bola no meio-campo, driblou três marcadores e acertou um chute de fora da área que ainda hoje é contado de geração em geração.',
      'Mais do que um gol, aquele lance virou patrimônio afetivo da cidade — prova de que o futebol de várzea também escreve sua própria épica.',
    ],
    comments: [],
  },
  {
    id: 'a5',
    title: 'Manchester City x Liverpool: prévia do duelo que pode decidir a Premier League',
    dek: 'Confronto direto entre líder e vice-líder acontece hoje, com ambos precisando da vitória.',
    category: 'Europa',
    author: 'Bianca Ferro',
    authorAvatar: 'https://i.pravatar.cc/150?img=29',
    date: '28 de julho de 2026',
    publishedAt: '2026-07-28T11:00:00.000Z',
    readTime: 5,
    image: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?auto=format&fit=crop&w=1200&q=80',
    body: [
      'A rodada decisiva da Premier League chega ao seu ápice hoje, com o duelo direto entre Manchester City e Liverpool, separados por apenas dois pontos na tabela.',
      'Especialistas apontam que o meio-campo será a chave tática da partida, com ambos os treinadores dispostos a arriscar formações mais ofensivas.',
    ],
    comments: [],
  },
  {
    id: 'a6',
    title: 'Corinthians e São Paulo empatam em clássico movimentado pela Copa do Brasil',
    dek: 'Timão e Tricolor ficam no 1 a 1 na Neo Química Arena, em jogo de vantagens alternadas.',
    category: 'Copa do Brasil',
    author: 'Marcos Villela',
    authorAvatar: 'https://i.pravatar.cc/150?img=12',
    date: '25 de julho de 2026',
    publishedAt: '2026-07-25T20:00:00.000Z',
    readTime: 4,
    image: 'https://images.unsplash.com/photo-1550881111-7cfde14b8073?auto=format&fit=crop&w=1200&q=80',
    body: [
      'Clássico paulista terminou empatado em 1 a 1 na Neo Química Arena, em confronto válido pela Copa do Brasil.',
      'O resultado deixa a decisão de vaga em aberto para o jogo de volta, que promete ser eletrizante.',
    ],
    comments: [],
  },
];
