export const seedTicker = [
  {
    id: 'm1',
    competition: 'Copa do Mundo 2022',
    homeTeam: 'Argentina',
    homeAbbr: 'ARG',
    awayTeam: 'França',
    awayAbbr: 'FRA',
    homeScore: 3,
    awayScore: 3,
    status: 'FIM',
    time: 'Final (pên: ARG)',
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'm2',
    competition: 'Champions League 2025',
    homeTeam: 'Paris Saint-Germain',
    homeAbbr: 'PSG',
    awayTeam: 'Inter de Milão',
    awayAbbr: 'INT',
    homeScore: 5,
    awayScore: 0,
    status: 'FIM',
    time: 'Final',
    createdAt: '2026-01-01T00:01:00.000Z',
  },
  {
    id: 'm3',
    competition: 'Libertadores 2023',
    homeTeam: 'Fluminense',
    homeAbbr: 'FLU',
    awayTeam: 'Boca Juniors',
    awayAbbr: 'BOC',
    homeScore: 2,
    awayScore: 1,
    status: 'FIM',
    time: 'Final',
    createdAt: '2026-01-01T00:02:00.000Z',
  },
  {
    id: 'm4',
    competition: 'Copa do Mundo 2018',
    homeTeam: 'França',
    homeAbbr: 'FRA',
    awayTeam: 'Croácia',
    awayAbbr: 'CRO',
    homeScore: 4,
    awayScore: 2,
    status: 'FIM',
    time: 'Final',
    createdAt: '2026-01-01T00:03:00.000Z',
  },
  {
    id: 'm5',
    competition: 'Libertadores 2019',
    homeTeam: 'Flamengo',
    homeAbbr: 'FLA',
    awayTeam: 'River Plate',
    awayAbbr: 'RIV',
    homeScore: 2,
    awayScore: 1,
    status: 'FIM',
    time: 'Final',
    createdAt: '2026-01-01T00:04:00.000Z',
  },
  {
    id: 'm6',
    competition: 'Champions League 2022',
    homeTeam: 'Real Madrid',
    homeAbbr: 'RMA',
    awayTeam: 'Liverpool',
    awayAbbr: 'LIV',
    homeScore: 1,
    awayScore: 0,
    status: 'FIM',
    time: 'Final',
    createdAt: '2026-01-01T00:05:00.000Z',
  },
  {
    id: 'm7',
    competition: 'Libertadores 2024',
    homeTeam: 'Botafogo',
    homeAbbr: 'BOT',
    awayTeam: 'Atlético Mineiro',
    awayAbbr: 'CAM',
    homeScore: 3,
    awayScore: 1,
    status: 'FIM',
    time: 'Final',
    createdAt: '2026-01-01T00:06:00.000Z',
  },
  {
    id: 'm8',
    competition: 'Champions League 2019',
    homeTeam: 'Liverpool',
    homeAbbr: 'LIV',
    awayTeam: 'Tottenham',
    awayAbbr: 'TOT',
    homeScore: 2,
    awayScore: 0,
    status: 'FIM',
    time: 'Final',
    createdAt: '2026-01-01T00:07:00.000Z',
  },
  {
    id: 'm9',
    competition: 'Libertadores 2021',
    homeTeam: 'Palmeiras',
    homeAbbr: 'PAL',
    awayTeam: 'Flamengo',
    awayAbbr: 'FLA',
    homeScore: 2,
    awayScore: 1,
    status: 'FIM',
    time: 'Final (prorrogação)',
    createdAt: '2026-01-01T00:08:00.000Z',
  },
  {
    id: 'm10',
    competition: 'Champions League 2016',
    homeTeam: 'Real Madrid',
    homeAbbr: 'RMA',
    awayTeam: 'Atlético de Madrid',
    awayAbbr: 'ATM',
    homeScore: 1,
    awayScore: 1,
    status: 'FIM',
    time: 'Final (pên: RMA)',
    createdAt: '2026-01-01T00:09:00.000Z',
  },
];
