export const seedTransfers = [
  {
    id: 't1',
    player: 'Memphis Depay',
    fromClub: 'Atlético de Madrid',
    toClub: 'Corinthians',
    status: 'Confirmado',
    probability: 100,
    detail: 'Contratação de peso do Corinthians: holandês chegou como reforço internacional badalado para o Timão.',
    year: 2024,
    country: 'Brasil',
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 't2',
    player: 'Luis Suárez',
    fromClub: 'Nacional',
    toClub: 'Grêmio',
    status: 'Confirmado',
    probability: 100,
    detail: 'Ídolo uruguaio reforçou o Grêmio de Renato Gaúcho após passagem pelo Nacional do Uruguai.',
    year: 2023,
    country: 'Brasil',
    createdAt: '2026-01-01T00:01:00.000Z',
  },
  {
    id: 't3',
    player: 'Daniele De Rossi',
    fromClub: 'Roma',
    toClub: 'Boca Juniors',
    status: 'Confirmado',
    probability: 100,
    detail: 'Ex-capitão da Roma surpreendeu ao assinar com o Boca Juniors, um dos maiores clubes da Argentina.',
    year: 2019,
    country: 'Argentina',
    createdAt: '2026-01-01T00:02:00.000Z',
  },
  {
    id: 't4',
    player: 'Edinson Cavani',
    fromClub: 'Valencia',
    toClub: 'Boca Juniors',
    status: 'Confirmado',
    probability: 100,
    detail: 'Matador uruguaio chegou ao Boca Juniors após passagem pelo Valencia, reforçando o ataque xeneize.',
    year: 2023,
    country: 'Argentina',
    createdAt: '2026-01-01T00:03:00.000Z',
  },
  {
    id: 't5',
    player: 'Dimitri Payet',
    fromClub: 'Olympique de Marseille',
    toClub: 'Vasco',
    status: 'Confirmado',
    probability: 100,
    detail: 'Craque francês trocou o Olympique de Marseille pelo Vasco da Gama, contratação histórica para São Januário.',
    year: 2023,
    country: 'Brasil',
    createdAt: '2026-01-01T00:04:00.000Z',
  },
  {
    id: 't6',
    player: 'Emmanuel Adebayor',
    fromClub: 'Kayserispor',
    toClub: 'Olimpia',
    status: 'Confirmado',
    probability: 100,
    detail: 'Ex-atacante do Arsenal e Real Madrid assinou com o Olimpia, gigante do futebol paraguaio.',
    year: 2020,
    country: 'Paraguai',
    createdAt: '2026-01-01T00:05:00.000Z',
  },
  {
    id: 't7',
    player: 'Keisuke Honda',
    fromClub: 'Vitesse',
    toClub: 'Botafogo',
    status: 'Confirmado',
    probability: 100,
    detail: 'Meia japonês, ex-Milan, chegou ao Botafogo como reforço internacional de peso.',
    year: 2020,
    country: 'Brasil',
    createdAt: '2026-01-01T00:06:00.000Z',
  },
  {
    id: 't8',
    player: 'Clarence Seedorf',
    fromClub: 'Milan',
    toClub: 'Botafogo',
    status: 'Confirmado',
    probability: 100,
    detail: 'Lenda do Milan e da Champions League surpreendeu o mundo ao assinar com o Botafogo.',
    year: 2012,
    country: 'Brasil',
    createdAt: '2026-01-01T00:07:00.000Z',
  },
  {
    id: 't9',
    player: 'Diego Forlán',
    fromClub: 'Inter de Milão',
    toClub: 'Internacional',
    status: 'Confirmado',
    probability: 100,
    detail: 'Ex-Manchester United e artilheiro da Copa do Mundo de 2010 reforçou o Internacional.',
    year: 2012,
    country: 'Brasil',
    createdAt: '2026-01-01T00:08:00.000Z',
  },
  {
    id: 't10',
    player: 'Deco',
    fromClub: 'Chelsea',
    toClub: 'Fluminense',
    status: 'Confirmado',
    probability: 100,
    detail: 'Campeão do mundo por Portugal, ex-Barcelona e Chelsea, chegou ao Fluminense para a reta final da carreira.',
    year: 2010,
    country: 'Brasil',
    createdAt: '2026-01-01T00:09:00.000Z',
  },
];
